
company:
  name: "Nord Transit Logistics"
  short_name: "NTL"

logging:
  directory: "./logs"
  json_format: true
  timestamp_format: "%Y-%m-%d %H:%M:%S"

networks:
  lille_hq: "192.168.10.0/24"
  wh1_lens: "192.168.20.0/24"
  wh2_valenciennes: "192.168.30.0/24"
  wh3_arras: "192.168.40.0/24"


infrastructure:
  ad_dns:
    - { ip: "192.168.10.10", name: "DC01", os: "Windows Server" }
    - { ip: "192.168.10.11", name: "DC02", os: "Windows Server" }
  windows_servers:
    - { ip: "192.168.10.10", name: "DC01", os: "windows", secret_ref: "win_admin" }
    - { ip: "192.168.10.11", name: "DC02", os: "windows", secret_ref: "win_admin" }
  linux_servers:
    - { ip: "192.168.10.21", name: "WMS-DB", os: "ubuntu", secret_ref: "wms_db_ssh" }
    - { ip: "192.168.10.22", name: "WMS-APP", os: "ubuntu", secret_ref: "wms_app_ssh" }
  wms:
    db_ip: "192.168.10.21"   # WMS-DB
    app_ip: "192.168.10.22"  # WMS-APP
    db_name: "wms_db"
diag:
  ad_ip:
    - '192.168.100.5'
    - '192.168.100.6'
audit:
  target_os: 
    - "ubuntu"
    - "windows"
    - "windows"
  mapping_os:
    "Windows 10" : "windows:10-22h2"
    "Ubuntu 20.04": "ubuntu:20.04"
    "Windows Server 2012 R2": "windows-server:2012-r2"
  network_range:
    - '127.0.0.1'
    - '192.168.150.0/24'
    - '192.168.100.0/24'
  csv_path: "data/list.csv" 
  audit_obsolescence_doc_path: "data/audit"
  audit_obsolescence_doc_path_csv: "data/audit/csv" 

thresholds:
  cpu_percent: 90
  ram_percent: 85
  disk_percent: 90


